[platformio]
default_envs = release, debug

[common]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -I${PROJECT_SRC_DIR}/drivers
    -I${PROJECT_SRC_DIR}/system
    -I${PROJECT_SRC_DIR}/screens
    -I${PROJECT_SRC_DIR}/assets
    -I${PROJECT_SRC_DIR}/logic
lib_deps =
    adafruit/Adafruit GFX Library
    WebServer
    DNSServer
    HTTPClient
    WiFiClientSecure

[env:release]
extends = common

[env:debug]
extends = common
build_flags =
    ${common.build_flags}
    -DDEBUG

[env:native]
platform = native
build_src_filter = -<*>
build_flags =
    -I${PROJECT_SRC_DIR}/logic
    -std=c++11
