[common]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    adafruit/Adafruit GFX Library

[env:release]
extends = common

[env:debug]
extends = common
build_flags =
    ${common.build_flags}
    -DDEBUG_GESTURES
